version: "3.8"

services:
  app: #  Go application service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        # this part ensures that the app only starts after the database is healthy
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_PORT: 5432

  db: # PostgreSQL database service
    image: postgres
    # this command ensures that we do the healthcheck before the app tries to connect to the database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
